name: CI & CD — Docker & Kubernetes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI_Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-kubernetes:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-kubernetes:${{ github.sha }}

  CD_Deploy:
    needs: CI_Push
    runs-on: [self-hosted, ec2-k3s]
    steps:
      - uses: actions/checkout@v4

      - name: Verify Kubernetes cluster access
        run: |
          sudo kubectl get nodes
          sudo kubectl get pods -A

      - name: Deploy to Kubernetes (use unique image tag)
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/hello-kubernetes:${{ github.sha }}
          echo "Deploying image: $IMAGE"
          sudo kubectl set image deployment/hello-kubernetes hello-kubernetes=$IMAGE --record
          sudo kubectl rollout status deployment/hello-kubernetes --timeout=120s
